CREATE TABLE account
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    company_id         BIGINT,
    balance            DECIMAL,
    latest_update_time TIMESTAMP WITHOUT TIME ZONE,
    active             BOOLEAN,
    CONSTRAINT pk_account PRIMARY KEY (id)
);