CREATE TABLE transaction
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_id      BIGINT,
    amount          DECIMAL,
    date            TIMESTAMP WITHOUT TIME ZONE,
    active          BOOLEAN,
    from_company_id BIGINT,
    CONSTRAINT pk_transaction PRIMARY KEY (id)
);